services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=fiap
      - POSTGRES_PASSWORD=fiap123
      - POSTGRES_DB=delivery
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  delivery:
    container_name: delivery
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres-db-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/delivery
      - SPRING_DATASOURCE_USERNAME=fiap
      - SPRING_DATASOURCE_PASSWORD=fiap123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    ports:
      - 8080:8080