openapi: 3.0.3

info:
  title: PósTech FIAP - Tech Challenge - 7SOAT
  description: |-
    Api para realização de pedidos num restaurante de fastfood
  version: 1.0.0

externalDocs:
  description: Sobre o projeto
  url: https://github.com/pricardoti/architecture-software-tech-challenge-fiap/wiki

servers:
  - url: http://localhost:8080/v1

tags:
  - name: "Cliente"
    description: "Tudo sobre o cliente"
  - name: "Produto"
    description: "Tudo sobre os produtos"
  - name: "Pedido"
    description: "Tudo sobre o pedido"

paths:
  /clientes:
    post:
      tags:
        - Cliente
      description: Tudo sobre o cliente
      requestBody:
        $ref: "#/components/requestBodies/ClienteResquest"
      responses:
        "201":
          $ref: "#/components/responses/ClienteResponse"

        "400":
          $ref: "#/components/responses/BadRequest"
    get:
      tags:
        - Cliente
      description: Tudo sobre o cliente
      parameters:
        - name: cpf
          in: query
          description: CPF do usuário
          required: false
          schema:
            type: string
            example: 72831839491
      responses:
        "200":
          $ref: "#/components/responses/ClientesReponse"

        "400":
          $ref: "#/components/responses/BadRequest"

  /clientes/{codigoCliente}:
    put:
      tags:
        - Cliente
      description: Atualização do Cliente
      parameters:
        - name: codigoCliente
          in: path
          description: Código do Cliente
          required: true
          schema:
            type: string
            example: d57b37c6-8842-41c2-9806-ec287d220dc7
      responses:
        "200":
          $ref: "#/components/responses/Sucess"
        "400":
          $ref: "#/components/responses/BadRequest"
    delete:
      tags:
        - Cliente
      description: Deletar o Cliente
      parameters:
        - name: codigoCliente
          in: path
          description: Código do Cliente
          required: true
          schema:
            type: string
            example: d57b37c6-8842-41c2-9806-ec287d220dc7
      responses:
        "200":
          $ref: "#/components/responses/Sucess"
        "400":
          $ref: "#/components/responses/BadRequest"


  /produtos:
    post:
      tags:
        - Produto
      description: Criar o produto
      requestBody:
        $ref: "#/components/requestBodies/ProdutoResquest"
      responses:
        "201":
          $ref: "#/components/responses/ProdutoResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
  /produtos/{codigoProduto}:
    put:
      tags:
        - Produto
      description: Atualizar o produto
      parameters:
        - name: codigoProduto
          in: path
          description: Código do Produto
          required: true
          schema:
            type: string
            example: d57b37c6-8842-41c2-9806-ec287d220dc7
      requestBody:
        $ref: "#/components/requestBodies/ProdutoResquest"
      responses:
        "200":
          $ref: "#/components/responses/Sucess"
        "400":
          $ref: "#/components/responses/BadRequest"
    delete:
      tags:
        - Produto
      description: Atualizar o produto
      parameters:
        - name: codigoProduto
          in: path
          description: Código do Produto
          required: true
          schema:
            type: string
            example: d57b37c6-8842-41c2-9806-ec287d220dc7
      responses:
        "200":
          $ref: "#/components/responses/Sucess"
        "400":
          $ref: "#/components/responses/BadRequest"
    get:
      tags:
        - Produto
      description: Buscar o produto
      parameters:
        - name: categoria
          in: query
          description: CPF do usuário
          required: false
          schema:
            type: string
            enum: [EM_PREPARACAO, PRONTO_ENTREGA, CANCELADO, FINALIZADO]
        - name: codigoProduto
          in: path
          description: Código do Produto
          required: true
          schema:
            type: string
            example: d57b37c6-8842-41c2-9806-ec287d220dc7
      responses:
        "201":
          $ref: "#/components/responses/ProdutosReponse"
        "400":
          $ref: "#/components/responses/BadRequest"


  /pedidos:
    post:
      tags:
        - Pedido
      description:
        Criar o pedido do cliente
      requestBody:
        $ref: "#/components/requestBodies/PedidoResquest"
      responses:
        "201":
          $ref: "#/components/responses/PedidoResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
    get:
      tags:
        - Pedido
      description:
        Criar o pedido do cliente
      parameters:
        - name: cpf
          in: query
          description: CPF do usuário
          required: false
          schema:
            type: string
            enum: [EM_PREPARACAO, PRONTO_ENTREGA, CANCELADO, FINALIZADO]
      responses:
        "200":
          $ref: "#/components/responses/PedidosReponse"
        "400":
          $ref: "#/components/responses/BadRequest"
  /pedidos/{codigoPedido}:
    patch:
      tags:
        - Pedido
      description:
        Criar o pedido do cliente
      parameters:
        - name: codigoPedido
          in: path
          description: Código do Pedido
          required: true
          schema:
            type: string
            example: d57b37c6-8842-41c2-9806-ec287d220dc7
      requestBody:
        $ref: "#/components/requestBodies/StatusPedidoResquest"
      responses:
        "200":
          $ref: "#/components/responses/Sucess"
  /pedidos/{codigoPedido}/checkout:
    post:
      tags:
        - Pedido
      description: Checkout do Pedido
      parameters:
        - name: codigoPedido
          in: path
          description: Código do Pedido
          required: true
          schema:
            type: string
            example: d57b37c6-8842-41c2-9806-ec287d220dc7
      requestBody:
        $ref: "#/components/requestBodies/StatusPedidoResquest"
      responses:
        "200":
          $ref: "#/components/responses/Sucess"


components:
  schemas:
    StatusPedido:
      type: object
      properties:
        status:
          type: string
          enum: [EM_PREPARACAO, PRONTO_ENTREGA, CANCELADO, FINALIZADO]



    Produto:
      type: "object"
      properties:
        nome:
          type: string
          description: "nome do produto"
          example: Batata Frita
        descricao:
          type: string
          description: "descricao do produto"
          example: Bebida 500ml
        preco:
          type: integer
          format: double
          description: "preco do produto"
          example: 12.75
        categoria:
          type: string
          description: "preco do produto"
          example: ACOMPANHAMENTO
        imagemUrl:
          type: string
          description: "imagem Url do produto"
          example: null
    Produtos:
      type: "object"
      properties:
        codigo:
          type: string
          example: fea06d61-3fd5-4475-8871-a88ebd5cb31d
        nome:
          type: string
          description: "nome do produto"
          example: Batata Frita
        descricao:
          type: string
          description: "descricao do produto"
          example: Bebida 500ml
        preco:
          type: integer
          format: double
          description: "preco do produto"
          example: 12.75
        categoria:
          type: string
          description: "preco do produto"
          example: ACOMPANHAMENTO
        imagemUrl:
          type: string
          description: "imagem Url do produto"
          example: null
    PedidosRetorno:
      type: object
      properties:
        codigoPedido:
          type: string
          example: dfcc5491-005e-416f-832d-a4ab6e835581
        cliente:
          type: string
          example: fd45d78e-9f33-46d4-9b54-f2f158d7b397
        valorTotal:
          type: integer
          format: duble
          example: 141.75
        produtos:
          type: array
          items:
            type: object
            properties:
              codigoProduto:
                type: string
                example: 257c13bd-ecc6-463c-bd5f-fc229180671e
              quantidade:
                type: integer
                format: int64
                example: 1


    Pedido:
      type: "object"
      properties:
        codigoCliente:
          type: string
          description: "id do pedido"
        produtos:
          type: array
          items:
            type: object
            properties:
              codigoProduto:
                type: string
                example: e2d931cb-140a-420e-a428-6c29fd2f2ba8
              quantidade:
                type: integer
                format: int64
                example: 2
    ClienteCadastro:
      type: "object"
      properties:
        cpf:
          type: string
          example: 72831839491
        nomeCompleto:
          type: string
          example: Clara Teresinha
        email:
          type: string
          example: mateus_duarte@focustg.com.br
        endereco:
          type: "object"
          properties:
            logradouro:
              type: string
              example: Rua Quatro de Outubro 1
            numero:
              type: string
              example: 955
            complemento:
              type: string
              example: Casa
            bairro:
              type: string
              example: Centro
            cidade:
              type: string
              example: Belem de Maria
            cep:
              type: string
              example: 55440-970
            uf:
              type: string
              example: PE
    ClienteRetorno:
      type: "object"
      properties:
        codigoCliente:
          type: string
          example: d57b37c6-8842-41c2-9806-ec287d220dc7
    PedidoRetorno:
      type: "object"
      properties:
        codigoPedido:
          type: string
          example: d57b37c6-8842-41c2-9806-ec287d220dc7
    ProdutoRetorno:
      type: "object"
      properties:
        codigoProduto:
          type: string
          example: d57b37c6-8842-41c2-9806-ec287d220dc7
    ClientesRetorno:
      type: "object"
      properties:
        codigo:
          type: string
          example: d57b37c6-8842-41c2-9806-ec287d220dc7
        cpf:
          type: string
          example: 72831839491
        nomeCompleto:
          type: string
          example: Clara Teresinha
        email:
          type: string
          example: mateus_duarte@focustg.com.br
        endereco:
          type: "object"
          properties:
            logradouro:
              type: string
              example: Rua Quatro de Outubro 1
            numero:
              type: string
              example: 955
            complemento:
              type: string
              example: Casa
            bairro:
              type: string
              example: Centro
            cidade:
              type: string
              example: Belem de Maria
            cep:
              type: string
              example: 55440-970
            uf:
              type: string
              example: PE

  requestBodies:
    ClienteResquest:
      description: Created user object
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ClienteCadastro"
    PedidoResquest:
      description: Created user object
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Pedido"
    ProdutoResquest:
      description: Created user object
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Produto"
    StatusPedidoResquest:
      description: Created user object
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StatusPedido"
  responses:
    ClientesReponse:
      description: Successful Operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/ClientesRetorno"
    ProdutosReponse:
      description: Successful Operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Produtos"
    PedidosReponse:
      description: Successful Operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/PedidosRetorno"

    ClienteResponse:
      description: Created
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ClienteRetorno"
    PedidoResponse:
      description: Created
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PedidoRetorno"
    ProdutoResponse:
      description: Created
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProdutoRetorno"
    BadRequest:
      description: Bad Request
    Sucess:
      description: Successful Operation