spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

api:
  pagamento:
    mercadopago:
      url: 'https://api.mercadopago.com'
      token: 'TEST-8025751384948506-072819-0d04b2e9dbbc225451d516a688b01c2a-33409927'