apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-delivery-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: delivery-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75