apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgresql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-postgresql-deployment
  template:
    metadata:
      labels:
        app: db-postgresql-deployment
    spec:
      containers:
        - name: postgresql-container
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-delivery-configmap
          volumeMounts:
            - name: db-postgresql-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: db-postgresql-storage
          emptyDir: {}
