apiVersion: v1
kind: Service
metadata:
  name: db-postgres-service
spec:
  selector:
    app: db-postgresql-deployment
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
